version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - tg_bot_net
  bot:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - tg_bot_net
volumes:
  db:
networks:
  tg_bot_net:
    driver: bridge